### ISSUE TITLE
L1 to L2 received transactions show up when the `pending` filter is applied

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/explorer#8]
When the `pending` filter is applied, I would not expect to see the already-received L1 -> L2 transactions on the explorer.

<img width="1725" alt="Screen Shot 2022-05-30 at 09 26 39" src="https://user-images.githubusercontent.com/9441295/171031858-ba7689cb-9132-4ddd-b930-2e5dcdaf712d.png">

**Comment by shanefontaine** [comment]
Yes, I believe it has been resolved with 501cf0661ba7bfeb3996fba8a014e2573c3294c7.

**Comment by peter44-a** [comment]
> Yes, I believe it has been resolved with 501cf0661ba7bfeb3996fba8a014e2573c3294c7. 

Alright
